/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myfirstproject.app;

class MessageUtils {
    public static String getMessage() {
        return "Qualquer mensagem";
    }
}
